import type { University } from "./types";

export const fallbackUniversities: University[] = [
  {
    id: "bristol",
    university_name: "University of Bristol",
    country: "United Kingdom",
    city: "Bristol",
    latitude: 51.4584,
    longitude: -2.603,
    image_url: "/images/university-covers/University%20of%20Bristol.jpg",
    summary: "영국 남서부 Bristol 도심에 자리한 연구 중심 대학입니다. 전공·관심 분야를 조합하는 Study Abroad 과정과 교환학생 지원 체계를 운영합니다.",
    official_website_url: "https://www.bristol.ac.uk/",
    incoming_exchange_url: "https://www.bristol.ac.uk/centre-for-study-abroad/",
    exchange_programs: [{
      id: "bristol-program", university_id: "bristol", academic_year: "2026/27", program_name: "Study Abroad", exchange_type: "International Exchange",
      application_process: "소속 대학의 선발·추천 이후 Bristol Study Abroad 지원 절차를 진행합니다.",
      course_registration_notes: "General pathway에서는 대학 전반의 과목을 조합할 수 있고, Subject pathway에서는 소속 학과 과목을 중심으로 수강합니다.",
      language_requirements: [{ test_type: "IELTS Academic", overall_score: 6.5, notes: "전공별 기준 확인 필요" }],
      academic_periods: [{ semester: "Autumn semester", start_text: "September 2026", end_text: "December 2026" }, { semester: "Spring semester", start_text: "January 2027", end_text: "May 2027" }],
      housing_options: [{ housing_category: "University accommodation", room_type: "Single / En suite / Twin", cost_text: "£1,709–£6,317", billing_period: "semester" }],
      estimated_costs: [{ cost_type: "Private monthly rent", original_text: "£500–£800+ / month" }],
      required_documents: [{ document_name: "소속 대학 추천 및 온라인 지원 서류", is_required: true }],
      source_links: [{ title: "Centre for Study Abroad", url: "https://www.bristol.ac.uk/centre-for-study-abroad/", is_official: true }],
    }],
  },
  {
    id: "edinburgh",
    university_name: "University of Edinburgh",
    country: "United Kingdom",
    city: "Edinburgh",
    latitude: 55.9445,
    longitude: -3.1892,
    image_url: "/images/university-covers/University%20of%20Edinburgh.jpg",
    summary: "스코틀랜드 Edinburgh 중심에 위치한 대학으로, 다양한 전공을 선택할 수 있는 International Exchange 및 방문학생 과정을 운영합니다.",
    official_website_url: "https://www.ed.ac.uk/",
    incoming_exchange_url: "https://global.ed.ac.uk/study-abroad",
    exchange_programs: [{
      id: "edinburgh-program", university_id: "edinburgh", academic_year: "2026/27", program_name: "International Exchange", exchange_type: "International Exchange",
      application_process: "온라인 지원에서 Nominated Exchange Student와 International Exchange를 선택하고 과목 및 증빙서류를 제출합니다.",
      course_registration_notes: "학기당 60 Edinburgh credits를 이수하며, 대체 과목을 고려해 최대 100 credits까지 희망 과목을 선택합니다.",
      application_deadlines: [{ semester: "Semester 1", deadline_text: "공식 Dates for your Diary에서 확인" }],
      language_requirements: [{ test_type: "IELTS Academic", overall_score: 6.5, score_details: { description: "각 영역 5.5 이상" } }, { test_type: "TOEFL iBT", overall_score: 92, score_details: { description: "각 영역 20 이상" } }],
      academic_periods: [{ semester: "Semester 1", start_date: "2026-09-21", end_date: "2026-12-21" }, { semester: "Semester 2", start_date: "2027-01-11", end_date: "2027-05-22" }],
      housing_options: [{ housing_category: "University housing", room_type: "Standard / Large ensuite", cost_text: "£8,658.40–£14,513.03", billing_period: "2026/27 academic year" }],
      estimated_costs: [{ cost_type: "Accommodation", original_text: "£8,658.40–£14,513.03 / academic year" }],
      required_documents: [{ document_name: "Official academic transcript", is_required: true }, { document_name: "Personal statement", is_required: true }, { document_name: "Course Ranking form", is_required: true }, { document_name: "English language certificate", is_required: true }],
      source_links: [{ title: "Edinburgh Global — Study Abroad", url: "https://global.ed.ac.uk/study-abroad", is_official: true }],
    }],
  },
];
